# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      

# Build steps
script:
  - cd hello_cmake
  - mkdir build
  - cd build
  - cmake ..
  - make
